version: "3.9"
services:
  mmstereo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mmattamala/mmstereo:pytorch2.0
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    volumes:
      - ../mmstereo:/root/catkin_ws/src/mmstereo
      - ../mmstereo_ros:/root/catkin_ws/src/mmstereo_ros
    command: '/bin/bash'